# Generated by Django 2.0 on 2018-04-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('action', models.TextField(verbose_name='Action')),
                ('priority', models.FloatField(verbose_name='Priority')),
            ],
        ),
    ]
