# Generated by Django 2.0 on 2018-04-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('werewolf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('game_key', models.CharField(max_length=15, verbose_name='Game Key')),
                ('state', models.CharField(choices=[('OP', 'Open Membership'), ('AS', 'Character Assignment'), ('VI', 'Character Viewing'), ('NI', 'Night Phase'), ('DI', 'Day Phase'), ('CL', 'Game Over')], default='OP', max_length=2, verbose_name='Game State')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='cur_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Character'),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='game_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game'),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='init_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='werewolf.Character'),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='werewolf.GameMembership'),
        ),
        migrations.AddField(
            model_name='game',
            name='night_sub_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.GameMembership'),
        ),
    ]
