# Generated by Django 2.0 on 2018-04-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0002_auto_20180421_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='night_sub_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='werewolf.GameMembership'),
        ),
        migrations.AlterField(
            model_name='gamemembership',
            name='cur_character',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='werewolf.Character'),
        ),
        migrations.AlterField(
            model_name='gamemembership',
            name='init_character',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='werewolf.Character'),
        ),
        migrations.AlterField(
            model_name='gamemembership',
            name='vote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='werewolf.GameMembership'),
        ),
    ]
